In [1]:
import pandas as pd
import os
import matplotlib.pyplot as plt
import json
import datetime

In [1]:
chat = open('./chat_exports/03 - 1004.txt', mode="r",encoding='utf-8').readlines()

In [3]:
timestamps =[]
contacts = []
messages = []

for line in chat:
    line= line.strip("\n")
    if line[6:10] == '2021':
        timestamps.append(line[:17])
        if len(line[20:].split(':'))==1:
            contacts.append('System Generated')
            messages.append(line[20:])
        else:
            contacts.append(line[20:].split(':')[0])
            messages.append("".join(line[20:].split(':')[1:])) #does remove ':' maar dat maakt niet uit.
    else:
        if len(line)>=1:
            messages[-1] +=line
df = pd.DataFrame({'Timestamp':timestamps,'Contact':contacts,'Message':messages}) 
df['Timestamp'] = pd.to_datetime(df['Timestamp'], dayfirst=True)
df = df[df['Contact']!='System Generated']
df = df.reset_index(drop=True)

In [68]:
df.iloc[100]['Timestamp'].month

4

In [91]:
a = datetime.date(2021, 4, 7)
b = a-datetime.timedelta(days=1)
p1 = df[(df['Timestamp'].dt.date==a) & (df['Timestamp'].dt.hour<19)]
p2 = df[(df['Timestamp'].dt.date==(a-datetime.timedelta(days=1))) & (df['Timestamp'].dt.hour>=19)]  
p3 = pd.concat([p2,p1])

In [92]:
p3

,Timestamp,Contact,Message
0,2021-04-06 22:35:00,Floris Beerens,Heuj
1,2021-04-07 12:21:00,Jelle Lauf,We gaan starten met Weervolven via Whatsapp. ...
2,2021-04-07 12:22:00,Jelle Lauf,Als aanvulling hierop. Vandaag wordt er ook g...
3,2021-04-07 12:33:00,Jelle Lauf,http//loulouapp.com/pollMain.php?tag=12090028...
4,2021-04-07 12:39:00,Marloes Heemskerk,Houdt er nog iemand een preek waarom ie burge...
...,...,...,...
68,2021-04-07 17:39:00,Betsie,Precies daar dacht ik ook aan. Het is wel zo ...
69,2021-04-07 17:42:00,Marloes Heemskerk,Het enige voordeel als er nu al iemand op de ...
70,2021-04-07 17:43:00,Marloes Heemskerk,Ik stem om pas na de eerste nacht iemand op d...
71,2021-04-07 17:51:00,Floris Beerens,Eens
72,2021-04-07 18:14:00,Rik De Leeuw,Die zat zeker in je buik bij het stemmen #roo...

In [81]:
b

datetime.date(2021, 4, 6)

In [73]:
p3

,Timestamp,Contact,Message
1,2021-04-07 12:21:00,Jelle Lauf,We gaan starten met Weervolven via Whatsapp. ...
2,2021-04-07 12:22:00,Jelle Lauf,Als aanvulling hierop. Vandaag wordt er ook g...
3,2021-04-07 12:33:00,Jelle Lauf,http//loulouapp.com/pollMain.php?tag=12090028...
4,2021-04-07 12:39:00,Marloes Heemskerk,Houdt er nog iemand een preek waarom ie burge...
5,2021-04-07 12:40:00,Jelle Lauf,Iedereen weet zijn rol nu als het goed is. Bi...
...,...,...,...
68,2021-04-07 17:39:00,Betsie,Precies daar dacht ik ook aan. Het is wel zo ...
69,2021-04-07 17:42:00,Marloes Heemskerk,Het enige voordeel als er nu al iemand op de ...
70,2021-04-07 17:43:00,Marloes Heemskerk,Ik stem om pas na de eerste nacht iemand op d...
71,2021-04-07 17:51:00,Floris Beerens,Eens
72,2021-04-07 18:14:00,Rik De Leeuw,Die zat zeker in je buik bij het stemmen #roo...

In [74]:
p1

,Timestamp,Contact,Message
1,2021-04-07 12:21:00,Jelle Lauf,We gaan starten met Weervolven via Whatsapp. ...
2,2021-04-07 12:22:00,Jelle Lauf,Als aanvulling hierop. Vandaag wordt er ook g...
3,2021-04-07 12:33:00,Jelle Lauf,http//loulouapp.com/pollMain.php?tag=12090028...
4,2021-04-07 12:39:00,Marloes Heemskerk,Houdt er nog iemand een preek waarom ie burge...
5,2021-04-07 12:40:00,Jelle Lauf,Iedereen weet zijn rol nu als het goed is. Bi...
...,...,...,...
68,2021-04-07 17:39:00,Betsie,Precies daar dacht ik ook aan. Het is wel zo ...
69,2021-04-07 17:42:00,Marloes Heemskerk,Het enige voordeel als er nu al iemand op de ...
70,2021-04-07 17:43:00,Marloes Heemskerk,Ik stem om pas na de eerste nacht iemand op d...
71,2021-04-07 17:51:00,Floris Beerens,Eens
72,2021-04-07 18:14:00,Rik De Leeuw,Die zat zeker in je buik bij het stemmen #roo...

In [79]:
p2

Empty DataFrame
Columns: [Timestamp, Contact, Message]
Index: []

In [76]:
df

,Timestamp,Contact,Message
0,2021-04-06 22:35:00,Floris Beerens,Heuj
1,2021-04-07 12:21:00,Jelle Lauf,We gaan starten met Weervolven via Whatsapp. ...
2,2021-04-07 12:22:00,Jelle Lauf,Als aanvulling hierop. Vandaag wordt er ook g...
3,2021-04-07 12:33:00,Jelle Lauf,http//loulouapp.com/pollMain.php?tag=12090028...
4,2021-04-07 12:39:00,Marloes Heemskerk,Houdt er nog iemand een preek waarom ie burge...
...,...,...,...
129,2021-04-08 15:36:00,Tom Mertens,Zo komt er toch nog een menselijk aspect aan ...
130,2021-04-08 15:38:00,Betsie,"Dan kunnen we morgen Jordi, Remco of Sven zo ..."
131,2021-04-08 15:42:00,Sven,Ik heb Jordi en Remco afgelopen dagen beide n...
132,2021-04-08 15:44:00,Jordi,Ik jullie ook niet. Ook zeer verdacht.
133,2021-04-08 15:44:00,Betsie,En Ilse en Et

In [90]:
df[(df['Timestamp'].dt.date==(b)) & (df['Timestamp'].dt.hour>=19)]

            Timestamp         Contact Message
0 2021-04-06 22:35:00  Floris Beerens    Heuj

In [88]:
a

datetime.date(2021, 4, 7)

In [89]:
b

datetime.date(2021, 4, 6)

In [104]:
df[['Contact','Message']].groupby(by='Contact').count().to_json()

'{"Message":{"Beau":4,"Betsie":9,"Bob":7,"Elise d\'Anjou":5,"Floris Beerens":14,"Jelle Lauf":19,"Joost De Laat":20,"Jordi":3,"Keely":5,"Manon Panis":4,"Marloes Heemskerk":17,"Martijn":2,"Pieter Kuijten":3,"Remco":5,"Rik De Leeuw":4,"Sven":2,"Tom Mertens":9,"\\u00c9ti\\u00ebnne Van Berkel":2}}'

In [116]:
type(a.strftime("%d-%m-%Y"))

str

In [118]:
for date in df['Timestamp'].dt.date.unique()[1:]:
    print(date)

2021-04-07
2021-04-08

In [2]:
def read_chat(chat):
    timestamps = []
    contacts = []
    messages = []

    for line in chat:
        line = line.strip("\n")
        if line[6:10] == '2021':
            timestamps.append(line[:17])
            if len(line[20:].split(':')) == 1:
                contacts.append('System Generated')
                messages.append(line[20:])
            else:
                contacts.append(line[20:].split(':')[0])
                messages.append("".join(line[20:].split(':')[1:]))  # does remove ':' maar dat maakt niet uit.
        else:
            if len(line) >= 1:
                messages[-1] += line
    df = pd.DataFrame({'Timestamp': timestamps, 'Contact': contacts, 'Message': messages})
    df['Timestamp'] = pd.to_datetime(df['Timestamp'], dayfirst=True)
    df = df[df['Contact'] != 'System Generated']
    df = df.reset_index(drop=True)
    # view of messages per contact:
    all_contacts = df[['Contact','Message']].groupby(by='Contact').count()
    return df, all_contacts

In [3]:
chat = open('./chat_exports/04 - 1804.txt', mode="r",encoding='utf-8').readlines()

In [4]:
df, contacts = read_chat(chat)

In [57]:
dead = {'2021-04-18 12:00:00':['Tom Mertens'],
       '2021-04-16 12:00:00':['Babet', 'Anke']}
df['Dood'] = 0 
for date in dead.keys():
    df['Dood'] = df.apply(lambda x: 1 if (x['Contact'] in dead[date]) & (x['Timestamp'] > pd.Timestamp(date)) else x['Dood'], axis=1)

In [58]:
df[-20:]

,Timestamp,Contact,Message,Dood
1328,2021-04-18 12:57:00,Elise d'Anjou,Ah shit... Die hadden we juist nodig,0
1329,2021-04-18 12:57:00,Ilse,O nee ðŸ˜¢,0
1330,2021-04-18 12:57:00,Beau,Ooh nee ðŸ˜­,0
1331,2021-04-18 12:58:00,Sven,ðŸ˜µ,0
1332,2021-04-18 13:00:00,Jordi,Maar meneer de burgemeester jij was gisteravo...,0
1333,2021-04-18 13:01:00,Joost De Laat,ðŸ˜±ðŸ˜±,0
1334,2021-04-18 13:03:00,Tom Mertens,Helaas heb ik Sven uiteindelijk alleen moeten...,1
1335,2021-04-18 13:09:00,Ã‰tiÃ«nne Van Berkel,ðŸ˜±,0
1336,2021-04-18 13:09:00,Ã‰tiÃ«nne Van Berkel,Niet de ziener,0
1337,2021-04-18 13:14:00,Tom Mertens,Om gerechtigheid voor zijn dood te krijgen mo...,1
1338,2021-04-18 13:16:00,Babet,âœ… Wie moet er op de brandstapel?http://www.lo...,1
1339,2021-04-18 13:24:00,Anke,Dit kan bijna geen toeval zijn,1
1340,2021-04-18 13:26:00,Elise d'Anjou,Hoe wisten ze dat sven de ziener was.. dit zo...,0
1341,2021-04-18 13:48:00,Marloes Heemskerk,Aaa nee! Onze troef is niet meer ðŸ˜­,0
1342,2021-04-18 13:49:00,Tom Mertens,"Nou, ik kan me niet bedenken hoe het niet ran...",1
1343,2021-04-18 13:50:00,Floris Beerens,Tja. Voor de voet weg maar iemand op de stape...,0
1344,2021-04-18 13:52:00,Bob,"Oh dit is niet droom, dikke pech ziener weg. ...",0
1345,2021-04-18 13:52:00,Pieter Kuijten,Vreselijk nieuws! ðŸ˜­ Dit is wel belangrijke in...,0
1346,2021-04-18 13:52:00,Bob,Ja als die wolven random 1 ziener kunnen rake...,0
1347,2021-04-18 13:53:00,Jelle Lauf,"Fuck, de ziener!",0

In [21]:
vote = pd.read_excel("./stemgedrag/01_1804_stemronde.xlsx")

In [22]:
vote

       Naam   Stem
0      Anke    Bob
1      Beau    Sam
2       Bob  Elise
3     Elise    Bob
4   Etienne  Elise
5    Floris   Beau
6      Ilse  Elise
7   Jasmijn    Bob
8     Jelle  Elise
9     Joost  Elise
10    Jordi    Bob
11  Marloes    Sam
12  Martijn    NaN
13   Pieter  Elise
14    Remco    Bob
15      Rik  Elise
16      Roy    Bob
17      Sam    Bob
18      Tom    Bob
19   Meeste    Bob

In [31]:

def generate_voting_table():
    vote_df = pd.DataFrame(columns=['Naam'])
    for file in os.listdir(".//stemgedrag//"):
        if 'stemronde' in file:
            tmp_df = pd.read_excel(".//stemgedrag//"+file)
            vote_df = vote_df.merge(tmp_df, how='outer', on='Naam')
    return vote_df

In [32]:
a= generate_voting_table()

In [63]:
import plotly.express as px
def create_contacts_graph(min_date, max_date):
    # filter dead people:
    df['Dood'] = 0
    for date in dead.keys():
        df['Dood'] = df.apply(
            lambda x: 1 if (x['Contact'] in dead[date]) & (x['Timestamp'] >= pd.Timestamp(date)) else x['Dood'], axis=1)

    df_filtered = df[(df['Timestamp'] >= min_date) & (df['Timestamp'] <= max_date)]
    df_contacts = df_filtered[["Contact", "Message"]].groupby(by='Contact').count().sort_values(by='Message',
                                                                                                ascending=False)
    df_contacts = df_contacts.merge(df_filtered[['Contact','Dood']].groupby(by='Contact').last(),left_index=True, right_index=True)
    figure = px.bar(df_contacts, x=df_contacts.index, y="Message", color='Dood', title='Berichten per persoon')
    return figure, df_filtered, df_contacts
a,b,c = create_contacts_graph('2021-04-16','2021-04-18')

In [73]:
min_date='2021-04-16'
max_date='2021-04-18'

df[(df['Timestamp'] >= min_date) & (df['Timestamp'] < (pd.Timestamp(max_date)+pd.Timedelta("1D")))]

,Timestamp,Contact,Message,Dood
1085,2021-04-16 11:56:00,Babet,We zijn begonnen!!âœ… Wie wordt de Burgemeester...,0
1086,2021-04-16 11:58:00,Jelle Lauf,Jasmijn! Geen idee waarom. Maar kleine mensje...,0
1087,2021-04-16 12:14:00,Sam,Hmm ik denk dat ik op iemand ga stemmen die k...,0
1088,2021-04-16 12:16:00,Floris Beerens,Jot. Kan ze lekker juffen,0
1089,2021-04-16 12:24:00,Bob,Een vrouwelijke burgemeester lijkt me ook wel...,0
...,...,...,...,...
1343,2021-04-18 13:50:00,Floris Beerens,Tja. Voor de voet weg maar iemand op de stape...,0
1344,2021-04-18 13:52:00,Bob,"Oh dit is niet droom, dikke pech ziener weg. ...",0
1345,2021-04-18 13:52:00,Pieter Kuijten,Vreselijk nieuws! ðŸ˜­ Dit is wel belangrijke in...,0
1346,2021-04-18 13:52:00,Bob,Ja als die wolven random 1 ziener kunnen rake...,0
1347,2021-04-18 13:53:00,Jelle Lauf,"Fuck, de ziener!",0

In [69]:
df

,Timestamp,Contact,Message,Dood
0,2021-04-06 22:35:00,Floris Beerens,Heuj,0
1,2021-04-07 12:21:00,Jelle Lauf,We gaan starten met Weervolven via Whatsapp. ...,0
2,2021-04-07 12:22:00,Jelle Lauf,Als aanvulling hierop. Vandaag wordt er ook g...,0
3,2021-04-07 12:33:00,Jelle Lauf,http//loulouapp.com/pollMain.php?tag=12090028...,0
4,2021-04-07 12:39:00,Marloes Heemskerk,Houdt er nog iemand een preek waarom ie burge...,0
...,...,...,...,...
1343,2021-04-18 13:50:00,Floris Beerens,Tja. Voor de voet weg maar iemand op de stape...,0
1344,2021-04-18 13:52:00,Bob,"Oh dit is niet droom, dikke pech ziener weg. ...",0
1345,2021-04-18 13:52:00,Pieter Kuijten,Vreselijk nieuws! ðŸ˜­ Dit is wel belangrijke in...,0
1346,2021-04-18 13:52:00,Bob,Ja als die wolven random 1 ziener kunnen rake...,0
1347,2021-04-18 13:53:00,Jelle Lauf,"Fuck, de ziener!",0

In [65]:
b

,Timestamp,Contact,Message,Dood
1085,2021-04-16 11:56:00,Babet,We zijn begonnen!!âœ… Wie wordt de Burgemeester...,0
1086,2021-04-16 11:58:00,Jelle Lauf,Jasmijn! Geen idee waarom. Maar kleine mensje...,0
1087,2021-04-16 12:14:00,Sam,Hmm ik denk dat ik op iemand ga stemmen die k...,0
1088,2021-04-16 12:16:00,Floris Beerens,Jot. Kan ze lekker juffen,0
1089,2021-04-16 12:24:00,Bob,Een vrouwelijke burgemeester lijkt me ook wel...,0
...,...,...,...,...
1320,2021-04-17 20:05:00,Bob,<Media omitted>,0
1321,2021-04-17 20:09:00,Jordi,"Dan ""leen"" je die toch gewoon",0
1322,2021-04-17 20:13:00,Babet,"Bii wie staat die, misschien kunnen de weerwo...",1
1323,2021-04-17 20:25:00,Marloes Heemskerk,Het eerste wat ik dacht was; chocolaaaaaðŸ˜¬,0
1324,2021-04-17 20:26:00,Marloes Heemskerk,ðŸ¤­,0

In [66]:
c

                    Message  Dood
Contact
Tom Mertens              36     0
Bob                      30     0
Floris Beerens           19     0
Jelle Lauf               17     0
Elise d'Anjou            16     0
Joost De Laat            16     0
Ã‰tiÃ«nne Van Berkel       15     0
Anke                     14     1
Marloes Heemskerk        13     0
Rik De Leeuw             12     0
Sam                       8     0
Jordi                     8     0
Babet                     7     1
Sven                      7     0
Remco                     5     0
Beau                      5     0
Ilse                      4     0
Jasmijn                   3     0
Pieter Kuijten            3     0
Martijn                   1     0
Roy                       1     0

In [39]:
df[['Contact','Dood']].groupby(by='Contact').last().index

Index(['Anke', 'Babet', 'Beau', 'Bob', 'Elise d'Anjou', 'Floris Beerens',
       'Ilse', 'Jasmijn', 'Jelle Lauf', 'Joost De Laat', 'Jordi', 'Keely',
       'Manon Panis', 'Marloes Heemskerk', 'Martijn', 'Pieter Kuijten',
       'Remco', 'Rik De Leeuw', 'Roy', 'Sam', 'Sven', 'Tom Mertens',
       'Ã‰tiÃ«nne Van Berkel'],
      dtype='object', name='Contact')

In [45]:
contacts.merge(df[['Contact','Dood']].groupby(by='Contact').last(),left_index=True,right_index=True)

                    Message  Dood
Contact
Anke                     17     0
Babet                    91     0
Beau                     30     0
Bob                      86     0
Elise d'Anjou            68     0
Floris Beerens           98     0
Ilse                     31     0
Jasmijn                  21     0
Jelle Lauf               72     0
Joost De Laat           108     0
Jordi                    30     0
Keely                    21     0
Manon Panis              19     0
Marloes Heemskerk        67     0
Martijn                   4     0
Pieter Kuijten           29     0
Remco                   144     0
Rik De Leeuw             32     0
Roy                      10     0
Sam                      13     0
Sven                     67     0
Tom Mertens             130     1
Ã‰tiÃ«nne Van Berkel      160     0

In [47]:
print(contacts.to_html())

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Message</th>
    </tr>
    <tr>
      <th>Contact</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Anke</th>
      <td>17</td>
    </tr>
    <tr>
      <th>Babet</th>
      <td>91</td>
    </tr>
    <tr>
      <th>Beau</th>
      <td>30</td>
    </tr>
    <tr>
      <th>Bob</th>
      <td>86</td>
    </tr>
    <tr>
      <th>Elise d'Anjou</th>
      <td>68</td>
    </tr>
    <tr>
      <th>Floris Beerens</th>
      <td>98</td>
    </tr>
    <tr>
      <th>Ilse</th>
      <td>31</td>
    </tr>
    <tr>
      <th>Jasmijn</th>
      <td>21</td>
    </tr>
    <tr>
      <th>Jelle Lauf</th>
      <td>72</td>
    </tr>
    <tr>
      <th>Joost De Laat</th>
      <td>108</td>
    </tr>
    <tr>
      <th>Jordi</th>
      <td>30</td>
    </tr>
    <tr>
      <th>Keely</th>
      <td>21</td>
    </tr>
    <tr>
      <th>Manon Panis</th>
      <td>19</td>
    </tr>
    <tr>
      <th>Marloes Heemskerk</th>
      <td>67</td>
    </tr>
    <tr>
      <th>Martijn</th>
      <td>4</td>
    </tr>
    <tr>
      <th>Pieter Kuijten</th>
      <td>29</td>
    </tr>
    <tr>
      <th>Remco</th>
      <td>144</td>
    </tr>
    <tr>
      <th>Rik De Leeuw</th>
      <td>32</td>
    </tr>
    <tr>
      <th>Roy</th>
      <td>10</td>
    </tr>
    <tr>
      <th>Sam</th>
      <td>13</td>
    </tr>
    <tr>
      <th>Sven</th>
      <td>67</td>
    </tr>
    <tr>
      <th>Tom Mertens</th>
      <td>130</td>
    </tr>
    <tr>
      <th>Ã‰tiÃ«nne Van Berkel</th>
      <td>160</td>
    </tr>
  </tbody>
</table>